### ISSUE TITLE
Crash with MetaMorpheus calibrated mzML

### ISSUE THREAD

**Issue by acesnik** [RonBeavis/SE#2]
Hi there,

I decided to test out SE today, and I'm getting an error with a calibrated mzML file from MetaMorpheus. Any idea what the issue is here?

Thanks!

AC

```
python se.py -d json/human.json
started ...

Loading parameters
.

Input parameters:
     spectra file: spectra/20100618_Velos1_TaGe_SA_U2OS_5-calib.mzML
     ptm depth: 2
     parent mass tolerance: 20
     parameter file: json/human.json
     output valid only: True
     output file: results/human.tsv
     mods v: {'M': [15995]}
     mods p: {'C': [57021, 57021], 'U': [57021, 57021], 'K': [0, 8014], 'R': [0, 10008]}
     mods o: {'nt-ammonia': True, 'nt-water': True}
     minimum peptide frequency: 1
     minimum identified intensity: 20.0
     kernel file: kernels/crap.KR.kernel.gz
     fragment mass tolerance: 20
     c13: True


Loading spectra
..   13.696 s

Loading kernels
....   2.019 s

Running ids
.Traceback (most recent call last):
  File "se.py", line 93, in <module>
    main()
  File "se.py", line 71, in main
    (ids,scores) = perform_ids(spectra,kmass,spectrum_list,params)
  File "/home/acesnik/se-install/perform_ids.py", line 64, in perform_ids
    s_set = dict(zip(s['sms'],s['ims']))
KeyError: 'ims'
```

**Comment by acesnik** [comment]
Here's the spectra file: https://www.dropbox.com/s/xxspoojz9of302u/20100618_Velos1_TaGe_SA_U2OS_5-calib.mzML?dl=0

**Comment by RonBeavis** [comment]
The problem was the script that cleans up mzML files hadn't been updated to match a change that I had made for the other file types. I've updated the 'load_spectra.py' file to correct the issue.

Thanks for taking the time to let me know about the problem.
